[package]
name = "bevy_tetris"
version = "0.1.0"
authors = ["makibishi <makibishi0212@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "0.10.1"
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3